sudo: required
dist: xenial
language: c
services:
- docker
before_install: make up
install: make
script:
- make test
- make smoke
- make coverage
deploy:
  provider: releases
  api_key:
    secure: a9bPGIbN3wwMyLs2r4BwOlgkQyzfTv2i8PEeY9gZNH2ICk1A8alRB0nK4Dx1qW4K88HUF+ieXdA8uozH3/3Nxw14LprGGLA3fXWx1eJyVdG2M5nivmJmWTwZhxNjQk87oGEOv8/wd8n4luXlnMCiXhxyuNSVEHWhts4MKWVUsTlaFRXkF93BbEJOA5gzNh0vqI69toytLIUZyYnronjQR1QSDusePLMsrKGKywpW1u5T1uP7GWJ121mTElkLl2TT2YAx63BCE+C8s7l3BiwbpPzJ9zkGEIX+oMqkPdezXQYYTfvazTFW7b09z75gD5I7gfNBCLuYgtlVVB0kNq8CJW3oP36EZv5J3oX53p1LadQmv0wBvYN5NHRPDyL47ZmjC/dIVgsRq+2lSQiud9fKuBFHXZatugqFZzinnuG0VDpn6YY4xtEsK7tROjF+SnMkIDlXU9H72ZOqzhy4/pCfolzzrcSM+l+OLn3rEMtyaZXSZ2GdRkzOYcuFpskWJPIDJ09FwUKTMWsRasA99FQYDTIG4U0zgyEMtn1fS6Efntyu7uypN1UnI9F28dUec8YjsQ0+D7mqf0bXMW/zE720i/E+e/obqNaG+xxZ0EQ0DIlknu1LZSI+UhNcWWr4LKc6UVNl9jRon4bhdC2ZrX2t9TzXCTCghXBV/aGrq167Jb0=
  file: deploy/oAuth1.xar
  skip_cleanup: true
  on:
    repo: grantmacken/oAuth1
    tags: true
    branch:
    - master
    - "/v\\d+\\.\\d+\\.\\d+/"
